### PR TITLE
Update local DB setup instructions in README (CU-g0tpd6)

### PR DESCRIPTION
**Pull request by trisapeace**
- Need to have the environment variables in sudo in order for the setup_postgresql_local.sh script to run correctly

This works for me on Ubuntu
@risatronic , you have a Mac right? Care you give it a shot there
@schwarrrtz , you're using Windows, right? Let's try them all!

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-g0tpd6 Fix environment variables for local setup scripts](https://app.clickup.com/t/g0tpd6)

**Comment by risatronic** [comment]
> * Need to have the environment variables in sudo in order for the setup_postgresql_local.sh script to run correctly
> 
> This works for me on Ubuntu
> @risatronic , you have a Mac right? Care you give it a shot there
> @schwarrrtz , you're using Windows, right? Let's try them all!

I do, but I run psql in a VM. I can set it up and see what happens though but part of why I'm using a VM is cause mac was being finicky about that in general so no promises haha

**Comment by trisapeace** [comment]
Don't worry about it @risatronic . I can try it on the Mac Mini instead. No point in getting into it if you know that it's a pain.

**Comment by risatronic** [comment]
> Don't worry about it @risatronic . I can try it on the Mac Mini instead. No point in getting into it if you know that it's a pain.

Okay if you're sure that's alright, thank you and sorry to not be more helpful! 😅

**Comment by trisapeace** [comment]
That style of adding environment variables seems to work for me on the Mac Mini. I couldn't get the rest of the postgres stuff working, but I think that's OK.

**Review by risatronic — APPROVED** [review]

**Review by mariocimet — APPROVED** [review]
looks good

**Comment by schwarrrtz** [comment]
This style of environment variable injection worked for me recently using `setup_postgres.sh`

**Review by schwarrrtz — APPROVED** [review]

**Pull request merged**
