### PR TITLE
ansible updates the comments in the remote access authorized_keys file

### PR DESCRIPTION
**Pull request by schwarrrtz**
I tested this while setting up the Minna Lee range test hub, and it seems to work well.

### CODE REVIEW

**Comment by trisapeace** [comment]
What changes, if any did you need to do in the config repo?
Is there a code review mechanism in CodeCommit?

**Comment by trisapeace** [comment]
Oh! Don't forget the CHANGELOG :smile:

**Comment by schwarrrtz** [comment]
No changes to the config repo, good catch on the changelog!

**Review by trisapeace — APPROVED** [review]
Looks good to me. Very cool. One less thing to worry about messing up, eh?

If there's a ClickUp task for this, could you please add it to the PR title and to the CHANGELOG?

**Comment by schwarrrtz** [comment]
There is no clickup task, this just came up while I was setting up the latest range test kit.

**Comment by mariocimet** [comment]
Looks good to me too

**Review by mariocimet — APPROVED** [review]

**Pull request merged**
