### PR TITLE
added PoE support to pi_config.ini and setup_pi.sh (CU-erwdt4)

### PR DESCRIPTION
**Pull request by schwarrrtz**

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-erwdt4 Handle PoE in pi_config.ini and setup_pi.sh](https://app.clickup.com/t/erwdt4)

**Review by mariocimet — APPROVED** [review]

**Comment by mariocimet** [comment]
Looks good! Saw you test this as well

**Comment by schwarrrtz** [comment]
@trisapeace and I talked about this yesterday and she gave her approval to merge this without a review from her.

**Review by trisapeace — COMMENTED** [review]
Oh good. Glad you got this one done without me. It looks like I would have had a difficult time parsing it out to tell whether it was good or not.

What is the other option for `flic_hub_interface` other than `eth0`?

**Comment by schwarrrtz** [comment]
@trisapeace currently the options are `eth0` or `eth1`, although theoretically there could be others. maybe this should be documented somewhere.

basically, with a regular (non-PoE) configuration we use `wlan0`, the wifi interface, to get internet into the RPi. then we use `eth0`, the builtin ethernet port on the RPi, to get internet from the RPi to the Flic hub.

with PoE, `eth0` is unavailable for the Flic hub connection because the ethernet cable carrying power is plugged into it. so we add a USB-to-serial adapter, `eth1`,  and connect the Flic hub to that instead.

**Comment by trisapeace** [comment]
Thanks for explaining. Documentation somewhere would probably be helpful.

**Pull request merged**
