### PR TITLE
Upgrade Chai and brave-alert-lib (CU-8678wgn0p)

### PR DESCRIPTION
**Pull request by trisapeace**
- To fix a high severity security issue: https://github.com/advisories/GHSA-4q6p-r6v2-jvc5

## Test plan
- [x] Travis passes

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-8678wgn0p Upgrade Chai in Buttons, Sensors, and brave-alert-lib](https://app.clickup.com/t/8678wgn0p)

**Review by tmackinnon — APPROVED** [review]
Looks good! Once Travis passes - good to go!

**Review by micahdbak — APPROVED** [review]
Looks good! So long as Travis passes---good to go!

**Review by ahmaddaadaa — APPROVED** [review]
looks good

**Pull request merged**
