### PR TITLE
Updating Braces Package (CU-86dtu06ga)

### PR DESCRIPTION
**Pull request by Darrickg**
Test Plan
- [x] npm test runs
- [x] travis runs

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-86dtu06ga Updating braces package to fix a vulnerability issue](https://app.clickup.com/t/86dtu06ga)

**Comment by Darrickg** [comment]
let me double check if travis runs before merging

**Comment by Darrickg** [comment]
travis didn't hate it!

**Review by johnny-brave — APPROVED** [review]
looks good, ready to merge

**Pull request merged**
