### PR TITLE
Remove hub modification endpoints (rename, mute, hide) (CU-dgm1bj)

### PR DESCRIPTION
**Pull request by trisapeace**
- These endpoints were insecure and most of us just change these values directly
  in the database. One day, they will be changeable through the
  Dashboard UI and that will be the safest way
- Love a pull request that does nothing but remove code, eh?

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-dgm1bj Remove heartbeat modification endpoints](https://app.clickup.com/t/dgm1bj)

**Review by schwarrrtz — COMMENTED** [review]
looks good.

**Comment by trisapeace** [comment]
Thanks. Do you approve @schwarrrtz ?

**Review by mariocimet — APPROVED** [review]

**Review by schwarrrtz — APPROVED** [review]
shoot, I thought I clicked approve. my bad.

**Pull request merged**
