### PR TITLE
Display all installations on dashboard (CU-fmudrh)

### PR DESCRIPTION
**Pull request by risatronic**
- Put list of installations into dropdown in nav bar
- Updated page to be responsive for ease of use on mobile/at smaller resolutions (mobile is zoomable but best in landscape)
- Removed unused nav bar from login.html, added some additional styling
- Added log out button to nav bar as route existed but had nothing directing to it
- Updated page titles to match dashboard nav (Brave Chatbot Dashboard), may want to change this if it will be called buttons in the future which I think is the case? But went with what the dashboard itself said for consistency

Note: changes are currently up on chatbot-dev if people are wanting to see them/ask for style revisions without much effort involved :)

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-fmudrh Should be able to access all the installations on the Chatbot Dashboard](https://app.clickup.com/t/fmudrh)

**Review by trisapeace — APPROVED** [review]
Looks great to me. Thanks for remembering to update the CHANGELOG.md!

**Comment by risatronic** [comment]
> Looks great to me. Thanks for remembering to update the CHANGELOG.md!

Thanks 😊

**Review by schwarrrtz — APPROVED** [review]
looks great!

**Pull request merged**
