### PR TITLE
Change master branch name to match preferred branching scheme (CU-mn5q4g)

### PR DESCRIPTION
**Pull request by trisapeace**
- Renamed `master` --> `main`
- Updated README and CHANGELOG accordingly
- Documentation here: https://app.clickup.com/2434616/v/dc/2a9hr-2261/2a9hr-4347
- Also fixed a 404 link in packages.json that had `master` in the URL

Once this pull request is approved, I will *not* merge it into `master`. Instead, I will 
1. Double-check that this branch is up-to-date with `master` (if not, then I'll rebase with `master`)
2. Update GitHub's default branch to be `main`
3. Change the target of all open pull requests from `master` to `main`
4. Delete the `master` branch

Once that is done, then the steps that I suggest everyone does on their local are:
1. Delete the `master` branch
2. Pull the `main` branch

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-mn5q4g Create set of instructions to move repos to main & production branch scheme](https://app.clickup.com/t/mn5q4g)

**Comment by schwarrrtz** [comment]
@trisapeace any idea why the following test is failing on Travis for this PR?

```
 db.js integration tests: getActiveAlertsByAlertApiKey

       if the session was longer ago than maxTimeAgoInMillis

         and it is WAITING_FOR_REPLY, should not return it:
```

**Comment by trisapeace** [comment]
@schwarrrtz Absolutely no idea. I wonder if it's a flaky test. That would suck. I will re-run it and see if it fails again.

Just noting the exact failure because Travis won't let me go back and look at it later if it passes the next time.
```
  1) db.js integration tests: getActiveAlertsByAlertApiKey
       if the session was longer ago than maxTimeAgoInMillis
         and it is WAITING_FOR_REPLY, should not return it:
      AssertionError: expected [ Array(1) ] to deeply equal []
      + expected - actual
      -[
      -  "9a29a496-b1f3-46d7-a5d3-476e973903ab"
      -]
      +[]
      
      at Context.<anonymous> (test/integration/dbTest/getActiveAlertsByAlertApiKeyTest.js:248:22)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by trisapeace** [comment]
Done!

**Pull request closed without merging**
