### PR TITLE
added audit-ci to Travis to check for security issues in server deps

### PR DESCRIPTION
**Pull request by schwarrrtz**
This pull request adds the same `audit-ci` tool to Travis as I added in this BraveAlert pull request: https://github.com/bravetechnologycoop/brave-alert-app/pull/11

### CODE REVIEW

**Review by trisapeace — APPROVED** [review]
Oh sweet, so this one already had no high security issues, that's really good news. I guess Dependabot was keeping us on our toes. Thanks!

**Comment by trisapeace** [comment]
@schwarrrtz Could you please add the same thing to Sensors while you're at it?

**Comment by schwarrrtz** [comment]
@trisapeace I haven't checked Sensors, but brave-alert-lib has audit issues that need to be fixed - I want to move on to other things instead of testing those changes, but I think it would be good to add `audit-ci` to all our Node repos eventually.

**Comment by trisapeace** [comment]
OK interesting. Thanks! I agree, it would be worth adding. How about adding a ClickUp Task for it for those other two repos?

**Review by mariocimet — APPROVED** [review]

**Pull request merged**
